# Generated by Django 3.1.7 on 2021-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_accepted',
            field=models.BooleanField(default=None),
        ),
    ]
