# Generated by Django 3.1.7 on 2021-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
