# Generated by Django 3.1.7 on 2021-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20210306_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
